/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.historico;

import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class FormHistorico extends javax.swing.JInternalFrame {
 
    /**
     * Creates new form FormHistorico
     */
    public FormHistorico() {
        
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomePet2 = new javax.swing.JTextField();
        bntSalvarTutor = new javax.swing.JButton();
        bntSalvarTutor2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        txtNomePet3 = new javax.swing.JTextField();
        bntSalvarTutor1 = new javax.swing.JButton();
        bntSalvarTutor3 = new javax.swing.JButton();

        txtNomePet2.setBackground(new java.awt.Color(204, 204, 204));
        txtNomePet2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtNomePet2.setBorder(null);

        bntSalvarTutor.setBackground(new java.awt.Color(102, 0, 102));
        bntSalvarTutor.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bntSalvarTutor.setForeground(new java.awt.Color(255, 255, 255));
        bntSalvarTutor.setText("Salvar");
        bntSalvarTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarTutorActionPerformed(evt);
            }
        });

        bntSalvarTutor2.setBackground(new java.awt.Color(102, 0, 102));
        bntSalvarTutor2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bntSalvarTutor2.setForeground(new java.awt.Color(255, 255, 255));
        bntSalvarTutor2.setText("Filtrar");
        bntSalvarTutor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarTutor2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Pet", "Especie", "Data", "Horário"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Histórico de Serviços");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtNomePet3.setBackground(new java.awt.Color(204, 204, 204));
        txtNomePet3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtNomePet3.setBorder(null);

        bntSalvarTutor1.setBackground(new java.awt.Color(102, 0, 102));
        bntSalvarTutor1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bntSalvarTutor1.setForeground(new java.awt.Color(255, 255, 255));
        bntSalvarTutor1.setText("Filtrar");
        bntSalvarTutor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarTutor1ActionPerformed(evt);
            }
        });

        bntSalvarTutor3.setBackground(new java.awt.Color(102, 0, 102));
        bntSalvarTutor3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bntSalvarTutor3.setForeground(new java.awt.Color(255, 255, 255));
        bntSalvarTutor3.setText("Fechar");
        bntSalvarTutor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarTutor3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bntSalvarTutor3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtNomePet3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bntSalvarTutor1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel21)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomePet3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntSalvarTutor1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(bntSalvarTutor3)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSalvarTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarTutorActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_bntSalvarTutorActionPerformed

    private void bntSalvarTutor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarTutor1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_bntSalvarTutor1ActionPerformed

    private void bntSalvarTutor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarTutor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntSalvarTutor2ActionPerformed

    private void bntSalvarTutor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarTutor3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bntSalvarTutor3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSalvarTutor;
    private javax.swing.JButton bntSalvarTutor1;
    private javax.swing.JButton bntSalvarTutor2;
    private javax.swing.JButton bntSalvarTutor3;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtNomePet2;
    private javax.swing.JTextField txtNomePet3;
    // End of variables declaration//GEN-END:variables
}
