/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.visualizar;

import dao.PetDAO;
import dao.TutorDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Pet;
import model.Tutor;

/**
 *
 * @author geova
 */
public class AlterarPet extends javax.swing.JFrame {

    /**
     * Creates new form AlterarPet
     */
    private Pet newPet;

    public AlterarPet(Pet petSelecionado) {
        initComponents();
        this.txtNomePet.setText(petSelecionado.getNomePet());
        this.txtRacaPet.setText(petSelecionado.getRacaPet());
        this.txtEspeciePet.setText(petSelecionado.getEspeciePet());

        // Formatando a data antes de exibir
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String dataNascPet = sdf.format(petSelecionado.getDataNascPet());
        this.txtDataNasc.setText(dataNascPet);

        // Selecionar o tutor associado ao pet no ComboBox
        this.comboBoxResponsavel.setSelectedItem(petSelecionado.getTutor());

        // Selecionar o sexo do pet nos RadioButtons
        if (petSelecionado.getSexoPet().equalsIgnoreCase("Macho")) {
            this.rbMacho.setSelected(true);
        } else {
            this.rbFemea.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtEspeciePet = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JTextField();
        btnSalvarAlteracao = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtNomePet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtRacaPet = new javax.swing.JTextField();
        rbMacho = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rbFemea = new javax.swing.JRadioButton();
        comboBoxResponsavel = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Alterar Tutor");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtEspeciePet.setBackground(new java.awt.Color(204, 204, 204));
        txtEspeciePet.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Data de Nascimento");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Responsável");

        txtDataNasc.setBackground(new java.awt.Color(204, 204, 204));
        txtDataNasc.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        btnSalvarAlteracao.setBackground(new java.awt.Color(204, 204, 204));
        btnSalvarAlteracao.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnSalvarAlteracao.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvarAlteracao.setText("Salvar");
        btnSalvarAlteracao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarAlteracaoMouseClicked(evt);
            }
        });
        btnSalvarAlteracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAlteracaoActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Sexo");

        txtNomePet.setBackground(new java.awt.Color(204, 204, 204));
        txtNomePet.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nome");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Raça");

        txtRacaPet.setBackground(new java.awt.Color(204, 204, 204));
        txtRacaPet.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        rbMacho.setBackground(new java.awt.Color(255, 255, 255));
        rbMacho.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        rbMacho.setForeground(new java.awt.Color(0, 0, 0));
        rbMacho.setText("Macho");
        rbMacho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbMachoMouseClicked(evt);
            }
        });
        rbMacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMachoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Espécie");

        rbFemea.setBackground(new java.awt.Color(255, 255, 255));
        rbFemea.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        rbFemea.setForeground(new java.awt.Color(0, 0, 0));
        rbFemea.setText("Fêmea");
        rbFemea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemeaActionPerformed(evt);
            }
        });

        comboBoxResponsavel.setToolTipText("");
        comboBoxResponsavel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                comboBoxResponsavelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(91, 91, 91)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(59, 59, 59)
                                            .addComponent(jLabel6)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(105, 105, 105)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(50, 50, 50)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnSalvarAlteracao)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(btnCancelar))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel8)
                                                    .addComponent(comboBoxResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtRacaPet, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(rbMacho)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(rbFemea)))))))
                                .addComponent(jLabel4)
                                .addComponent(txtNomePet, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEspeciePet, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRacaPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomePet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEspeciePet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbMacho)
                            .addComponent(rbFemea))
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarAlteracao)
                    .addComponent(btnCancelar))
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarAlteracaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarAlteracaoMouseClicked
        PetDAO petDAO = new PetDAO();

        String nomePet = this.txtNomePet.getText();
        String racaPet = this.txtRacaPet.getText();
        String especiePet = this.txtEspeciePet.getText();
        String dataNascPet = this.txtDataNasc.getText();
        Tutor tutorPet = (Tutor) this.comboBoxResponsavel.getSelectedItem();
        if (rbMacho.isSelected()) {
            String sexoPet = this.rbMacho.getText();
            newPet = new Pet(nomePet, racaPet, especiePet, dataNascPet, sexoPet, tutorPet);
        } else {
            String sexoPet = this.rbFemea.getText();
            newPet = new Pet(nomePet, racaPet, especiePet, dataNascPet, sexoPet, tutorPet);
        }

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

        try {
            Date data = dateFormat.parse(dataNascPet);

        } catch (ParseException ex) {
            ex.printStackTrace();
        }

        petDAO.editar(newPet);

        if (txtNomePet.getText().equals("") || txtRacaPet.getText().equals("") || txtEspeciePet.getText().equals("") || txtDataNasc.getText().equals("") || comboBoxResponsavel.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        } else {
            JOptionPane.showMessageDialog(null, "Pet alterado com sucesso!");
            this.dispose();
            VisualizarPet visualizarPet = new VisualizarPet();
            visualizarPet.setVisible(true);
        }
    }//GEN-LAST:event_btnSalvarAlteracaoMouseClicked

    private void btnSalvarAlteracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAlteracaoActionPerformed
        // TODO add your handling code here:
        //        int cod = 1;
        //        Pet p = new Pet();
        //        p.setCodPet(cod);
        //        p.setNomePet(txtNomePet.getText());
        //        p.setRacaPet(txtRacaPet.getText());
        //        p.setEspeciePet(txtEspeciePet.getText());
        //        p.setDataNascPet(txtDataNasc.getText());

    }//GEN-LAST:event_btnSalvarAlteracaoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void rbMachoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbMachoMouseClicked
        //        rbMacho = (String)"Macho";
    }//GEN-LAST:event_rbMachoMouseClicked

    private void rbMachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMachoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMachoActionPerformed

    private void rbFemeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemeaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFemeaActionPerformed

    private void comboBoxResponsavelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_comboBoxResponsavelAncestorAdded
        TutorDAO tutorDAO = new TutorDAO();
        ArrayList<Tutor> tutores = tutorDAO.selecionar();

        this.comboBoxResponsavel.removeAll();

        for (Tutor t : tutores) {
            this.comboBoxResponsavel.addItem(t);
        }
    }//GEN-LAST:event_comboBoxResponsavelAncestorAdded

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(Pet petSelecionado) {
                new AlterarPet(petSelecionado).setVisible(true);
            }

            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvarAlteracao;
    private javax.swing.JComboBox comboBoxResponsavel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbFemea;
    private javax.swing.JRadioButton rbMacho;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtEspeciePet;
    private javax.swing.JTextField txtNomePet;
    private javax.swing.JTextField txtRacaPet;
    // End of variables declaration//GEN-END:variables
}
