/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.visualizar;

import dao.PetDAO;
import dao.TutorDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.Tutor;

/**
 *
 * @author lucas
 */
public class VisualizarTutor extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormVisualizar
     */
    private TutorDAO tutorDAO;
    private PetDAO petDAO;

    public VisualizarTutor() {
        initComponents();
        this.tutorDAO = new TutorDAO();
        this.petDAO = new PetDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDadosTutor = new javax.swing.JTable();
        bntSalvarTutor = new javax.swing.JButton();
        bntEditarTutor = new javax.swing.JButton();
        btnExcluirTutor = new javax.swing.JButton();
        bntSalvarTutor3 = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Visualizar Tutor");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Visualizar  Tutor");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbDadosTutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Tutor", "Nome", "CPF", "Email", "Telefone", "Endereço"
            }
        ));
        jScrollPane1.setViewportView(tbDadosTutor);

        bntSalvarTutor.setBackground(new java.awt.Color(102, 0, 102));
        bntSalvarTutor.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bntSalvarTutor.setForeground(new java.awt.Color(255, 255, 255));
        bntSalvarTutor.setText("Buscar Tutores");
        bntSalvarTutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntSalvarTutorMouseClicked(evt);
            }
        });

        bntEditarTutor.setBackground(new java.awt.Color(102, 0, 102));
        bntEditarTutor.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bntEditarTutor.setForeground(new java.awt.Color(255, 255, 255));
        bntEditarTutor.setText("Editar");
        bntEditarTutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntEditarTutorMouseClicked(evt);
            }
        });

        btnExcluirTutor.setBackground(new java.awt.Color(102, 0, 102));
        btnExcluirTutor.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnExcluirTutor.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirTutor.setText("Excluir");
        btnExcluirTutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExcluirTutorMouseClicked(evt);
            }
        });

        bntSalvarTutor3.setBackground(new java.awt.Color(102, 0, 102));
        bntSalvarTutor3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        bntSalvarTutor3.setForeground(new java.awt.Color(255, 255, 255));
        bntSalvarTutor3.setText("Sair");
        bntSalvarTutor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSalvarTutor3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bntSalvarTutor)
                                .addGap(35, 35, 35)
                                .addComponent(bntEditarTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(btnExcluirTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(301, 301, 301)
                                .addComponent(bntSalvarTutor3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(275, 275, 275)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel21)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntSalvarTutor)
                    .addComponent(bntEditarTutor)
                    .addComponent(btnExcluirTutor)
                    .addComponent(bntSalvarTutor3))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntSalvarTutor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSalvarTutor3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bntSalvarTutor3ActionPerformed

    private void bntSalvarTutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntSalvarTutorMouseClicked
        ArrayList<Tutor> tutores = tutorDAO.selecionar();
        DefaultTableModel model = (DefaultTableModel) tbDadosTutor.getModel();
        model.setNumRows(0);

        for (int i = 0; i < tutores.size(); i++) {
            model.addRow(new String[]{String.valueOf(tutores.get(i).getCodTutor()), tutores.get(i).getNomeTutor(), tutores.get(i).getCpfTutor(), tutores.get(i).getEmailTutor(), tutores.get(i).getTelefoneTutor(), tutores.get(i).getEnderecoTutor()});
        }
    }//GEN-LAST:event_bntSalvarTutorMouseClicked

    private void bntEditarTutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntEditarTutorMouseClicked
        // TODO add your handling code here:
        int linhaSelecionada = tbDadosTutor.getSelectedRow();

        if (linhaSelecionada != -1) {
            Object valor = tbDadosTutor.getValueAt(linhaSelecionada, 0);
            int idTutor = Integer.parseInt((String) valor);

            Tutor tutorSelecionado = tutorDAO.selecionarPorCodigo(idTutor);

            if (tutorSelecionado != null) {
                AlterarTutor alterarTutor = new AlterarTutor(tutorSelecionado);
                this.dispose();
                alterarTutor.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Tutor não encontrado.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma linha para editar.");
        }
    }//GEN-LAST:event_bntEditarTutorMouseClicked

    private void btnExcluirTutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirTutorMouseClicked
        // TODO add your handling code here:
        int linhaSelecionada = tbDadosTutor.getSelectedRow();

        if (linhaSelecionada != -1) {
            int idTutor = Integer.parseInt((String) tbDadosTutor.getValueAt(linhaSelecionada, 0));

            petDAO.excluirPetsPorTutor(idTutor);
            tutorDAO.excluir(idTutor);

            Tutor tutor = tutorDAO.selecionarPorCodigo(idTutor);

            if (tutor != null) {
                JOptionPane.showMessageDialog(null, "Tente novamente");
            } else {
                JOptionPane.showMessageDialog(null, "Tutor excluído com sucesso!");
            }
            //            atualizarTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um tutor para excluir.");
        }
    }//GEN-LAST:event_btnExcluirTutorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEditarTutor;
    private javax.swing.JButton bntSalvarTutor;
    private javax.swing.JButton bntSalvarTutor3;
    private javax.swing.JButton btnExcluirTutor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDadosTutor;
    // End of variables declaration//GEN-END:variables
}
